import { FormEvent, useEffect, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, Eye, EyeOff } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Logo } from "@/components/ogcraft/logo";

export const Route = createFileRoute("/auth")({
  head: () => ({ meta: [{ title: "Log in — OGCraft" }, { name: "description", content: "Sign in or create your OGCraft account." }, { property: "og:title", content: "Log in — OGCraft" }, { property: "og:description", content: "Sign in to build and manage dynamic social preview images." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: AuthPage,
});
function AuthPage() {
  const navigate = useNavigate(); const [mode, setMode] = useState<"login" | "signup" | "forgot">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [show, setShow] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { supabase.auth.getUser().then(({ data }) => { if (data.user) navigate({ to: "/dashboard", replace: true }); }); }, [navigate]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); if (mode === "forgot") { const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/reset-password` }); setMessage(error?.message ?? "Check your email for a password reset link."); setBusy(false); return; } if (mode === "signup") { const { data, error } = await supabase.auth.signUp({ email, password, options: { emailRedirectTo: window.location.origin, data: { full_name: name } } }); setMessage(error?.message ?? (data.session ? "Account created." : "Check your email to confirm your account.")); if (data.session) navigate({ to: "/dashboard" }); } else { const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) setMessage(error.message); else navigate({ to: "/dashboard" }); } setBusy(false); }
  async function google() { setBusy(true); const { error } = await supabase.auth.signInWithOAuth({ provider: "google", options: { redirectTo: window.location.origin } }); if (error) { setMessage(error.message); setBusy(false); return; } }
  return <main className="auth-shell"><Link to="/" className="absolute left-5 top-5 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Back</Link><div className="auth-panel"><Logo /><div className="mt-8"><p className="font-mono text-[10px] uppercase text-primary">Developer access</p><h1 className="mt-2 text-3xl font-semibold">{mode === "login" ? "Welcome back" : mode === "signup" ? "Create your account" : "Reset your password"}</h1><p className="mt-2 text-sm text-muted-foreground">{mode === "forgot" ? "We'll send a secure reset link to your inbox." : "Generate production-ready OG images in milliseconds."}</p></div>{mode !== "forgot" && <Button variant="outline" className="mt-7 w-full" onClick={google} disabled={busy}><span className="font-bold">G</span> Continue with Google</Button>}{mode !== "forgot" && <div className="my-5 flex items-center gap-3 text-[10px] uppercase text-muted-foreground"><span className="h-px flex-1 bg-border" /> or email <span className="h-px flex-1 bg-border" /></div>}<form className="space-y-4" onSubmit={submit}>{mode === "signup" && <label className="block space-y-2"><Label>Display name</Label><Input required value={name} onChange={(e) => setName(e.target.value)} /></label>}<label className="block space-y-2"><Label>Email</Label><Input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label>{mode !== "forgot" && <label className="block space-y-2"><Label>Password</Label><div className="relative"><Input required minLength={8} type={show ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} className="pr-10" /><Button type="button" variant="ghost" size="icon" className="absolute right-0 top-0" onClick={() => setShow(!show)} aria-label={show ? "Hide password" : "Show password"}>{show ? <EyeOff /> : <Eye />}</Button></div></label>}{message && <p className="rounded-md border border-border bg-muted/50 p-3 text-xs text-muted-foreground">{message}</p>}<Button className="w-full" disabled={busy}>{busy ? "Please wait…" : mode === "login" ? "Log in" : mode === "signup" ? "Create free account" : "Send reset link"}</Button></form><div className="mt-5 flex justify-between text-xs"><button type="button" className="text-muted-foreground hover:text-foreground" onClick={() => setMode(mode === "signup" ? "login" : "signup")}>{mode === "signup" ? "Already have an account?" : "Create an account"}</button>{mode !== "forgot" && <button type="button" className="text-muted-foreground hover:text-foreground" onClick={() => setMode("forgot")}>Forgot password?</button>}{mode === "forgot" && <button type="button" className="text-muted-foreground hover:text-foreground" onClick={() => setMode("login")}>Back to login</button>}</div></div></main>;
}
