import { FormEvent, useEffect, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Logo } from "@/components/ogcraft/logo";
export const Route = createFileRoute("/reset-password")({ head: () => ({ meta: [{ title: "Reset password — OGCraft" }, { name: "description", content: "Choose a new password for your OGCraft account." }, { property: "og:title", content: "Reset password — OGCraft" }, { property: "og:description", content: "Securely reset your OGCraft account password." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: ResetPassword });
function ResetPassword() { const navigate = useNavigate(); const [password, setPassword] = useState(""); const [ready, setReady] = useState(false); const [message, setMessage] = useState(""); useEffect(() => { const hash = new URLSearchParams(window.location.hash.slice(1)); setReady(hash.get("type") === "recovery" || Boolean(hash.get("access_token"))); }, []); async function submit(e: FormEvent) { e.preventDefault(); const { error } = await supabase.auth.updateUser({ password }); if (error) setMessage(error.message); else { setMessage("Password updated. Redirecting…"); setTimeout(() => navigate({ to: "/dashboard" }), 900); } } return <main className="auth-shell"><div className="auth-panel"><Logo /><h1 className="mt-8 text-3xl font-semibold">Set a new password</h1>{ready ? <form onSubmit={submit} className="mt-7 space-y-4"><label className="block space-y-2"><Label>New password</Label><Input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{message && <p className="text-sm text-muted-foreground">{message}</p>}<Button className="w-full">Update password</Button></form> : <p className="mt-4 text-sm text-muted-foreground">This recovery link is missing or expired. <Link to="/auth" className="text-primary">Request a new one.</Link></p>}</div></main>; }
