import { Link } from "@tanstack/react-router";
import { ArrowRight, BookOpen, Boxes, Check, Code2, Github, Image, Layers3, Menu, Radio, Sparkles, X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Logo } from "./logo";

const links = [{ label: "Features", to: "/features" }, { label: "Playground", to: "/playground" }, { label: "Pricing", to: "/pricing" }, { label: "Docs", to: "/docs" }] as const;
export function PublicNav() { const [open, setOpen] = useState(false); return <header className="fixed inset-x-0 top-0 z-50 mx-auto max-w-5xl px-4 pt-4"><div className="flex min-h-14 items-center justify-between rounded-xl border border-border/80 bg-background/80 px-3 shadow-nav backdrop-blur-xl"><Link to="/" aria-label="OGCraft home"><Logo /></Link><nav className="hidden items-center gap-1 md:flex">{links.map((item) => <Button variant="ghost" size="sm" asChild key={item.to}><Link to={item.to}>{item.label}</Link></Button>)}</nav><div className="hidden items-center gap-2 md:flex"><Button variant="ghost" size="sm" asChild><Link to="/auth">Log in</Link></Button><Button size="sm" asChild><Link to="/auth">Get API Key Free <ArrowRight /></Link></Button></div><Button size="icon" variant="ghost" className="md:hidden" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X /> : <Menu />}</Button></div>{open && <div className="mt-2 rounded-xl border border-border bg-card p-2 shadow-panel md:hidden">{links.map((item) => <Button variant="ghost" className="w-full justify-start" asChild key={item.to}><Link to={item.to} onClick={() => setOpen(false)}>{item.label}</Link></Button>)}<Button className="mt-2 w-full" asChild><Link to="/auth">Get API Key Free</Link></Button></div>}</header>; }
export function PublicFooter() { return <footer className="border-t border-border/70"><div className="mx-auto flex max-w-6xl flex-col gap-5 px-5 py-10 sm:flex-row sm:items-center sm:justify-between"><Logo /><p className="text-xs text-muted-foreground">Dynamic images, built for the open web.</p><nav className="flex flex-wrap gap-5 text-xs text-muted-foreground"><a href="https://github.com" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 hover:text-foreground"><Github className="size-3.5" /> GitHub</a><Link to="/docs" className="hover:text-foreground">Docs</Link><a href="/privacy" className="hover:text-foreground">Privacy</a><a href="/status" className="hover:text-foreground">Status</a></nav></div></footer>; }
export const featureItems = [{ icon: Radio, title: "Edge-fast rendering", text: "Every image is generated close to your audience and cached automatically." }, { icon: Code2, title: "One URL API", text: "Ship production-ready social cards with a single URL and predictable parameters." }, { icon: Layers3, title: "Composable templates", text: "Start with polished defaults, then tune content, colors, logos, and layout." }, { icon: Boxes, title: "Framework agnostic", text: "Use OGCraft with Next.js, plain HTML, Astro, Shopify, or any HTTP client." }];
export const plans = [{ name: "Free", price: "$0", text: "For personal projects and prototypes.", features: ["100 images / month", "Starter templates", "OGCraft watermark"] }, { name: "Pro", price: "$12", text: "For products ready to grow.", popular: true, features: ["5,000 images / month", "Custom templates", "No watermark"] }, { name: "Agency", price: "$39", text: "For teams shipping at scale.", features: ["50,000 images / month", "Team access", "Ultra-low latency"] }];
export function FeatureGrid() { return <div className="grid gap-px overflow-hidden rounded-xl border border-border bg-border md:grid-cols-2">{featureItems.map((item) => <article key={item.title} className="bg-background p-7"><span className="icon-box"><item.icon /></span><h3 className="mt-5 font-semibold">{item.title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">{item.text}</p></article>)}</div>; }
export function PricingGrid() { return <div className="grid gap-4 lg:grid-cols-3">{plans.map((plan) => <article key={plan.name} className={`relative rounded-lg border p-7 ${plan.popular ? "border-primary bg-primary/5 shadow-glow" : "border-border bg-card/50"}`}>{plan.popular && <span className="absolute right-5 top-5 rounded-full bg-primary px-2.5 py-1 text-[10px] font-semibold uppercase text-primary-foreground">Popular</span>}<p className="text-sm font-medium">{plan.name}</p><p className="mt-5 text-4xl font-semibold">{plan.price}<span className="text-sm font-normal text-muted-foreground">/mo</span></p><p className="mt-2 text-sm text-muted-foreground">{plan.text}</p><ul className="mt-7 space-y-3">{plan.features.map((item) => <li key={item} className="flex items-center gap-2 text-sm"><Check className="size-4 text-success" />{item}</li>)}</ul><Button variant={plan.popular ? "default" : "outline"} className="mt-8 w-full" asChild><Link to="/auth">{plan.name === "Free" ? "Start free" : `Choose ${plan.name}`}</Link></Button></article>)}</div>; }
export function PageIntro({ eyebrow, title, text, icon: Icon = Sparkles }: { eyebrow: string; title: string; text: string; icon?: typeof Sparkles }) { return <div className="mx-auto max-w-3xl pt-36 text-center"><span className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1.5 font-mono text-[10px] uppercase text-primary"><Icon className="size-3" />{eyebrow}</span><h1 className="mt-6 text-4xl font-semibold leading-tight sm:text-6xl">{title}</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-muted-foreground">{text}</p></div>; }
export function CtaBand() { return <section className="border-t border-border/70"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 px-5 py-20 sm:flex-row sm:items-center"><div><p className="font-mono text-xs uppercase text-primary">Ship the preview</p><h2 className="mt-2 text-3xl font-semibold">One URL. Every social card.</h2></div><Button size="lg" asChild><Link to="/auth">Start free <ArrowRight /></Link></Button></div></section>; }
